title: Software Developer Blog
description: Francisco Dorado - Software Developer
author: Francisco Dorado
github: https://github.com/frandorado
about: I am a software developer focused on back-end and specialized in Java and Spring.
disqus_shortname: frandorado
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/
  cv:
    output: true
    permalink: /cv/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/frandorado"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/franciscodorado"
    - icon: fa-github
      link: "https://github.com/frandorado"

share:
  twitter_username: frandorado

urls:
    - text: About Me
      url: /about/
    - text: CV
      url: /cv/resume
      childs:
        - text: Work Experience
          url: /cv/work-experience
        - text: Skills
          url: /cv/skills
        - text: Education and Training
          url: /cv/education-training
    - text: Projects
      url: /projects/
    - text: Statistics
      url: /statistics/
    - text: Feed RSS
      url: /feed.xml

url: "https://frandorado.github.io"
baseurl: ""
counterUrl: "https://doradofran.pythonanywhere.com"
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
